### ISSUE TITLE
Document index page not showing correctly in browser

### ISSUE THREAD

**Issue by tatafarewell** [gpilab/gpilab.github.io#1]
JRE version 1.8.0_60
Browser: Firefox 35.0.1
![screenshot from 2015-10-22 02 58 20](https://cloud.githubusercontent.com/assets/7292016/10655947/4198f9c0-78ac-11e5-8405-42a4af60e25b.png)

**Comment by nckz** [comment]
Renders correctly in the current version of Firefox (41).
